### ISSUE TITLE
Wrong number of args (2) passed to: static-roam.core/-main

### ISSUE THREAD

**Issue by thams** [TomLisankie/static-roam#11]
Exception in thread "main" Syntax error compiling at (/tmp/form-init4958262423806450754.clj:1:73).
	at clojure.lang.Compiler.load(Compiler.java:7647)
	at clojure.lang.Compiler.loadFile(Compiler.java:7573)
	at clojure.main$load_script.invokeStatic(main.clj:452)
	at clojure.main$init_opt.invokeStatic(main.clj:454)
	at clojure.main$init_opt.invoke(main.clj:454)
	at clojure.main$initialize.invokeStatic(main.clj:485)
	at clojure.main$null_opt.invokeStatic(main.clj:519)
	at clojure.main$null_opt.invoke(main.clj:516)
	at clojure.main$main.invokeStatic(main.clj:598)
	at clojure.main$main.doInvoke(main.clj:561)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.Var.applyTo(Var.java:705)
	at clojure.main.main(main.java:37)
Caused by: clojure.lang.ArityException: Wrong number of args (2) passed to: static-roam.core/-main
	at clojure.lang.AFn.throwArity(AFn.java:429)
	at clojure.lang.AFn.invoke(AFn.java:36)
	at clojure.lang.Var.invoke(Var.java:388)
	at user$eval140.invokeStatic(form-init4958262423806450754.clj:1)
	at user$eval140.invoke(form-init4958262423806450754.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:7176)
	at clojure.lang.Compiler.eval(Compiler.java:7166)
	at clojure.lang.Compiler.load(Compiler.java:7635)
	... 12 more

**Comment by TomLisankie** [comment]
What were you trying to do that brought about this error?

**Comment by thams** [comment]
user error. 
Forgot to include "degree".

That said, I don't know what "degree" is supposed to represent.

**Comment by thams** [comment]
Also, I stumbled onto this link: 
https://twitter.com/TomLisankie/status/1267891965053546507
which says I needed to tag a block with #EntryPoint
You might want to add that to the README along with the explanation of "degree."

**Comment by TomLisankie** [comment]
Will do within the next couple of days. Definitely should have been in the README from the beginning, agreed.

Just so you know though, this project will likely be overshadowed in these next few months by a similar project I've been working on.

Are you just looking to experiment with static-roam or are you trying to really build something with / on top of it?

**Comment by thams** [comment]
experimenting.

the immediate objective is to be able to share some of my Roam pages with people who do not have Roam accounts.

The particular use case is for annotating an article that has been copied/pasted from the web, and preserve Roam's links between annotations and blocks within the article.

**Comment by TomLisankie** [comment]
@thams please checkout #12 which addresses some of your concerns.
